name: CI-CD Pipeline

on:
  push:
    branches:
      - main

jobs:

  build:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 17

    - name: Build Application
      run: mvn clean package

    - name: SonarQube Analysis
      run: |
        mvn sonar:sonar \
        -Dsonar.projectKey=sample-app \
        -Dsonar.host.url=${{ secrets.SONAR_HOST }} \
        -Dsonar.token=${{ secrets.SONAR_TOKEN }}

    - name: Deploy Artifact to Nexus
      run: mvn deploy
      env:
        NEXUS_USERNAME: ${{ secrets.NEXUS_USERNAME }}
        NEXUS_PASSWORD: ${{ secrets.NEXUS_PASSWORD }}

    - name: Deploy to Tomcat
      run: |
        curl -u "${{ secrets.TOMCAT_USERNAME }}:${{ secrets.TOMCAT_PASSWORD }}" \
        -T target/file-upload-url-generator \
        "http://${{ secrets.TOMCAT_HOST }}:8080/manager/text/deploy?path=/file-upload-url-generator&update=true"
